### PR TITLE
EventSourcing Workshop

### PR DESCRIPTION
**Pull request by razco**
Worked with Ilay Zeidman @ilayze

My branch name: csharp-workshop
My tags: csharp-raz-solution-<version.subVersion>  ie: csharp-raz-solution-1.1

@robi-y  eventSourcing workshop completed (3 first steps: 1.1 - 3.2)

### CODE REVIEW

**Comment by robi-y** [comment]
Nice, did you learn something from it? (@ilayze)
Will appreciate help to your mates in the coming lecture

**Comment by razco** [comment]
We didn't learn much from it because we didn't spend enough time about this subject in lessons. We felt like we did a technical job, but didn't fully understand how to implement it in a new system from scratch..

On the other hand, on personal note, I felt the git-immeresion workshop was very beneficial. Probably the most beneficial I've had so far! Knowing git is extremely important and practically helpful. I've started using it in work on regular basis (in my job we used only the basic commands of "git citool" and "git push/pull"). I didn't just write the commands of workshop git-immerrsion in order to show the commits in my repo, I tried to understand each command deeper (it took me hours), and it turned into a smart decision.

Thanks a lot

**Comment by ilayze** [comment]
I also think the git immersion was really good I would have spent even more time on it and even go deeper to understand the scenarios when working with group and what can go wrong.

**Comment by robi-y** [comment]
Actually the final lecture next week will be a revisit to git model mainly
based on this one:
http://www.infoq.com/presentations/git-details
https://github.com/jherland/git_parable
You're invited...
Thanks

**Pull request closed without merging**
